from modal_dictation_exploration.types.sounddevice import DeviceInfo, HostApiInfo

def query_hostapis() -> tuple[HostApiInfo, ...]: ...
def query_devices(device: int) -> DeviceInfo: ...

class PortAudioError(Exception): ...
